from typing import TypedDict, Optional
from src.utils.logger import logging

logging.info("Initializing DevTeamState schema for DevTeam workflow")

class DevTeamState(TypedDict):
    """
    Typed state container shared across all LangGraph agent nodes.

    Each field represents an artifact produced or consumed by a specific
    agent in the AUTOSAR SWS software development lifecycle:

    ┌──────────────────────┬────────────────────────────────────────────────┐
    │  Field               │  Producing Agent                               │
    ├──────────────────────┼────────────────────────────────────────────────┤
    │  user_request        │  User input (initial seed)                     │
    │  autosar_context     │  RAG retrieval from uploaded AUTOSAR SWS PDF   │
    │  product_spec        │  ProductManagerAgent                           │
    │  architecture        │  ArchitectAgent                                │
    │  code                │  DeveloperAgent                                │
    │  tests               │  QAAgent                                       │
    │  review              │  CodeReviewAgent                               │
    │  error               │  Any agent (failure propagation)               │
    └──────────────────────┴────────────────────────────────────────────────┘

    """

    # Initial user input describing the software requirement
    user_request: str
   
    # Autosar retrieval context generated by RAGAgent from uploaded AUTOSAR SWS PDF
    autosar_context: str
  
    # Product specification generated by ProductManagerAgent
    product_spec: str

    # System architecture designed by ArchitectAgent
    architecture: str

    # Backend code generated by DeveloperAgent
    code: str

    # Unit tests generated by QAAgent
    tests: str

    # Code review feedback generated by CodeReviewAgent
    review: str
