import os
import sys
from src.utils.logger import logging
from src.utils.exception import CustomException

class LogReader:
    """
    LogReader is responsible for reading CAN log files (.asc)
    and returning raw log lines.

    These logs are typically generated by Vector CANoe or CANalyzer.
    """

    def read_logs(self, file_path: str):
        """
        Read a CAN log file and return raw lines.

        Parameters
        ----------
        file_path : str
            Path to the CAN log (.asc) file.

        Returns
        -------
        list
            List containing all lines from the log file.
        """

        try:
            logging.info(f"Reading CAN log file: {file_path}")

            # -------------------------------------------------
            # Check if the log file exists
            # -------------------------------------------------
            if not os.path.exists(file_path):
                logging.error(f"Log file not found: {file_path}")
                raise FileNotFoundError(f"Log file not found: {file_path}")

            # -------------------------------------------------
            # Open the log file in read mode
            # -------------------------------------------------
            with open(file_path, "r", encoding="utf-8") as file:
                lines = file.readlines()

            logging.info(f"Successfully read {len(lines)} lines from log file")

            return lines

        except Exception as e:
            logging.error("Error occurred while reading the CAN log file")
            raise CustomException(e, sys)