import operator
import warnings
from typing_extensions import TypedDict
from typing import Annotated, Any, List, Dict, Optional
warnings.filterwarnings("ignore")

class SearchResult(TypedDict):
    """
    Output from Search Agent (Tavily or similar)

    Attributes:
        url (str): Source URL
        title (str): Page title
        snippet (str): Short preview text
        query (str): Query used to fetch this result
    """
    url: str
    title: str
    snippet: str
    query: str

class ExtractedData(TypedDict):
    """
    Output from Extraction Agent

    Attributes:
        themes (List[Dict]): Key themes/topics identified
        key_stats (List[str]): Important statistics or numbers
        notable_quotes (List[str]): Extracted quotes
        source_urls (List[str]): URLs used for extraction
    """
    themes: List[Dict[str, Any]]
    key_stats: List[str]
    notable_quotes: List[str]
    source_urls: List[str]

class ReviewFeedback(TypedDict):
    """
    Output from Review Agent

    Attributes:
        approved (bool): Whether report is acceptable
        issues (List[str]): Problems found
        suggestions (List[str]): Improvements suggested
        overall_score (int): Quality score (e.g., 1–10)
    """
    approved: bool
    issues: List[str]
    suggestions: List[str]
    overall_score: int
        
class ResearchState(TypedDict):
    """
    Central shared state for LangGraph multi-agent workflow.

    This state is passed and updated across agents:
        - Search Agent
        - Extraction Agent
        - Writer Agent
        - Reviewer Agent

    Attributes:
        topic (str): User input topic

        research_plan (str): Plan generated by planner agent (optional)

        search_queries (List[str]): Queries generated for search

        raw_search_results (List[SearchResult]):
            Aggregated search results (accumulates across steps)

        extracted_data (Optional[ExtractedData]):
            Structured insights from extraction agent

        draft_report (str): Initial report by writer agent

        final_report (str): Final polished report

        review_feedback (Optional[ReviewFeedback]):
            Feedback from reviewer agent

        revision_count (int): Number of revisions made

        errors (List[str]):
            Captured errors during workflow execution

        messages (List[Dict]):
            Optional: agent communication / trace logs
    """

    topic: str
    research_plan: str
    search_queries: List[str]
    raw_search_results: Annotated[List[SearchResult], operator.add]
    extracted_data: Optional[ExtractedData]
    draft_report: str
    final_report: str
    review_feedback: Optional[ReviewFeedback]
    revision_count: int
    errors: Annotated[List[str], operator.add]
    messages: Annotated[List[Dict], operator.add]       
